name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Déploiement automatique uniquement sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le code
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Configurer Python et installer les dépendances
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Étape 3 : Déployer avec l'API PythonAnywhere
    - name: Deploy using PythonAnywhere API
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        echo "Début du déploiement via l'API PythonAnywhere..."

        # Installer jq pour analyser les réponses JSON
        sudo apt-get install jq

        # 1. Créer une nouvelle console pour exécuter les commandes
        RESPONSE=$(curl -s -X POST \
          -H "Authorization: Token ${PA_API_TOKEN}" \
          -d '{"executable": "/bin/bash"}' \
          https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/consoles/)
        CONSOLE_ID=$(echo $RESPONSE | jq -r '.id')
        echo "Console ID: $CONSOLE_ID"

        # 2. Se connecter et récupérer les dernières modifications du dépôt GitHub
        echo "Mise à jour des fichiers via git pull..."
        curl -s -X POST \
          -H "Authorization: Token ${PA_API_TOKEN}" \
          -d "workon venv && cd /home/${PA_USERNAME}/DjangoAuthentification && git pull" \
          https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/consoles/${CONSOLE_ID}/send_input/

        # 3. Exécuter les commandes Django nécessaires (makemigrations, migrate, collectstatic)
        echo "Exécution des commandes Django..."
        curl -s -X POST \
          -H "Authorization: Token ${PA_API_TOKEN}" \
          -d "workon venv && cd /home/${PA_USERNAME}/DjangoAuthentification && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput" \
          https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/consoles/${CONSOLE_ID}/send_input/

        # 4. Redémarrer l'application web
        echo "Redémarrage de l'application web..."
        RESPONSE=$(curl -s -X POST \
          -H "Authorization: Token ${PA_API_TOKEN}" \
          https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/webapps/${PA_USERNAME}.pythonanywhere.com/reload/)
        echo "Réponse du redémarrage: $RESPONSE"

        echo "Déploiement terminé avec succès !"