name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Déploiement automatique uniquement sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le code
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Configurer Python et installer les dépendances
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Étape 3 : Déployer avec l'API PythonAnywhere
    - name: Deploy using PythonAnywhere API
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        echo "Début du déploiement via l'API PythonAnywhere..."

        # Étape 3.1 : Mettre à jour les fichiers nécessaires
        echo "Mise à jour des fichiers..."
        curl -X POST \
          -H "Authorization: Token ${PA_API_TOKEN}" \
          -F "content=@requirements.txt" \
          https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/files/path/home/${PA_USERNAME}/DjangoAuthentification/requirements.txt

        # Étape 3.2 : Installer les dépendances avec pip
        echo "Installation des dépendances..."
        curl -X POST \
          -H "Authorization: Token ${PA_API_TOKEN}" \
          -d "command=workon venv && cd /home/${PA_USERNAME}/DjangoAuthentification && pip install django" \
          https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/consoles/

        # Étape 3.3 : Exécuter les commandes Django nécessaires
        echo "Exécution des commandes Django..."
        curl -X POST \
          -H "Authorization: Token ${PA_API_TOKEN}" \
          -d "command=workon venv && cd /home/${PA_USERNAME}/DjangoAuthentification && python manage.py makemigrations" \
          https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/consoles/

        curl -X POST \
          -H "Authorization: Token ${PA_API_TOKEN}" \
          -d "command=workon venv && cd /home/${PA_USERNAME}/DjangoAuthentification && python manage.py migrate" \
          https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/consoles/

        curl -X POST \
          -H "Authorization: Token ${PA_API_TOKEN}" \
          -d "command=workon venv && cd /home/${PA_USERNAME}/DjangoAuthentification && python manage.py collectstatic --noinput" \
          https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/consoles/

        # Étape 3.4 : Redémarrer l'application web
        echo "Redémarrage de l'application web..."
        curl -X POST \
          -H "Authorization: Token ${PA_API_TOKEN}" \
          https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/webapps/${PA_USERNAME}.pythonanywhere.com/reload/

        echo "Déploiement terminé avec succès !"
