name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Déploiement automatique uniquement sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le code
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Configurer Python et installer les dépendances
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Étape 3 : Déployer avec l'API PythonAnywhere
    - name: Deploy using PythonAnywhere API
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        echo "Début du déploiement via l'API PythonAnywhere..."

        # 1. Se connecter et récupérer les dernières modifications du dépôt GitHub
        echo "Mise à jour des fichiers via git pull..."
        RESPONSE=$(curl -s -X GET \
          -H "Authorization: Token ${PA_API_TOKEN}" \
          "https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/consoles/37410353/?command=workon venv && cd /home/${PA_USERNAME}/DjangoAuthentification && git pull")
        echo "Réponse du git pull: $RESPONSE"

        # 2. Exécuter les commandes Django nécessaires (makemigrations, migrate, collectstatic)
        echo "Exécution des commandes Django..."
        RESPONSE=$(curl -s -X GET \
          -H "Authorization: Token ${PA_API_TOKEN}" \
          "https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/consoles/37410353/?command=workon venv && cd /home/${PA_USERNAME}/DjangoAuthentification && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput")
        echo "Réponse des commandes Django: $RESPONSE"

        # 3. Redémarrer l'application web
        echo "Redémarrage de l'application web..."
        RESPONSE=$(curl -s -X POST \
          -H "Authorization: Token ${PA_API_TOKEN}" \
          https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/webapps/${PA_USERNAME}.pythonanywhere.com/reload/)
        echo "Réponse du redémarrage: $RESPONSE"

        echo "Déploiement terminé avec succès !"