name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Déploiement automatique uniquement sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le code
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Configurer Python et installer les dépendances
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pythonanywhere

    # Étape 3 : Déployer avec l'API PythonAnywhere
    - name: Deploy using PythonAnywhere API
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        echo "Début du déploiement via l'API PythonAnywhere..."

        # Mettre à jour le code sur PythonAnywhere
        curl -X POST -u "${PA_USERNAME}:${PA_API_TOKEN}" \
          https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/files/path/home/${PA_USERNAME}/DjangoAuthentification/.git/ \
          -F content=@.git/

        # Redémarrer l'application web
        curl -X POST -u "${PA_USERNAME}:${PA_API_TOKEN}" \
          https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/webapps/${PA_USERNAME}.pythonanywhere.com/reload/

        echo "Déploiement terminé avec succès !"
